# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tag',
        ),
    ]
