# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 15:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20161209_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='tagname',
        ),
    ]
